# Generated by Django 5.0.6 on 2024-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=122)),
                ('content_markdown', models.TextField(default='')),
                ('image', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
